### ISSUE TITLE
updated docs

### ISSUE THREAD

**Issue by kfox1111** [bjhaid/pam_hook#10]
The docs in the kubeconf section look outdated as compared to lower where it is talking about TokenRequests (implies you can use it as a kubectl auth plugin now)

**Comment by bjhaid** [comment]
@kfox1111 it's unclear which part of the doc you are referring to can you open a PR with a suggestion?

**Comment by kfox1111** [comment]
oh. I missed the line after the kubeconf saying it was a kubeconf for the apiserver, not the user's kubeconf.

Do you have a kubeconf example for users?

**Comment by bjhaid** [comment]
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://kube.bar.com/
  name: bar
contexts:
- context:
    cluster: bar
    user: replace_with_username
  name: bar
current-context: bar
kind: Config
preferences: {}
users:
- name: replace_with_username
  user:
    as-user-extra: {}
    token: replace_with_token_from_received_from_pamhook
```
